services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    env_file:
      - .env_npm
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm
      - DB_MYSQL_NAME=npm
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks: 
      - proxy

  db:
    image: 'jc21/mariadb-aria:latest'
    env_file:
      - .env_db
    environment:
      - MYSQL_ROOT_PASSWORD=npm
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks: 
      - proxy

  duckdns:
    image: linuxserver/duckdns
    deploy:
      resources:
        limits:
          memory: 70M
        reservations:
          memory: 40M
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env_duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
        # timezone
      - TZ=America/new_york
        # accept multiple domains, use comma. Ex: domain1.duckdns.org,domain2.duckdns.org,domain3.duckdns.org
      - SUBDOMAINS=suso-portainer.duckdns.org
        # Token duckdns
      - TOKEN=50a3fcd6-4aed-4d06-8c73-4a293103a42b

    networks: 
      - proxy

networks:
  proxy:
    # Specify driver options
    driver: proxy_default
